on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  sdist:
    runs-on: ubuntu-20.04
    steps:
    - name: clone repo
      uses: actions/checkout@v4

  linux:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - spec: cp27-manylinux_x86_64
          cibw_version: cibuildwheel<2.0  # py2.7 is not supported on CIBW 2.0+
          manylinux_img: manylinux1  # build really old Pythons on manylinux1
        - spec: cp36-manylinux_x86_64
          manylinux_img: manylinux1  # build really old Pythons on manylinux1
        - spec: cp37-manylinux_x86_64
        - spec: cp38-manylinux_x86_64
        - spec: cp39-manylinux_x86_64
    steps:
    - name: clone repo
      uses: actions/checkout@v4


  macos:
    defaults:
      run:
        shell: ${{ matrix.run_wrapper || 'bash --noprofile --norc -eo pipefail {0}' }}
    runs-on: ${{ matrix.runs_on || 'macos-11' }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - spec: cp39-macosx_x86_64

    steps:
    - name: clone repo
      uses: actions/checkout@v2
      if: ${{ matrix.maybe_skip != 'skip' }}

  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
        - spec: cp39-win_amd64
    steps:
    - name: clone repo
      uses: actions/checkout@v4

  summary:
    if: always()
    needs:
    - sdist
    - linux
    - macos
    - windows
    runs-on: ubuntu-latest
    steps:
    - name: Provide a summary validation check job
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

